# range(start, stop, step)


# Parameters :::
    
# start → Number to start from (default is 0)

# stop → Number to stop before

# step → How much to increase each time (default is 1) 
                 #OR
#  step →means how much to jump each time. 


"""  NOTE 
Here we used list () in each eaxample .
list() is used to convert the range object into a list 
 allowing us to see all the numbers generated by range()."""


""""  NOTE  
# We use list() only when we want to see all the numbers
# generated by range() at once.
# In a for loop, list() is not needed because the for loop
# automatically reads the numbers from range() one by one."""


# EXAMPLE 1 :: 
# list(range(4))    # stop  (0,4) ::>>  0 (default)

# output : [0, 1, 2, 3]
  
# # EXAMPLE 2:: 
# list(range(1,6)) # range(start , stop) 

# output : [1, 2, 3, 4 ,5]
    
# #EXAMPLE 3:: 
""""Here, list() is used only to display all the values in the range object at once"""
# list(range(1,10,2)) # range(start , stop , step)  # step = step means how much to jump each time. 

# output : [1, 3, 5, 7, 9] jumped by 2 

# # How it works 

# # Start = 1
# # Stop = 10 (10 is not included)
# # Step = 2 (jump by 2)
         
         
#          #NOTE :: WE CAN ALSO WRITE THE PRINT THE NUBER IN REVERSE 
         
# list(range(12,0,-1))         
         
# OUTPUT :: [12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


# # Explanation ::
# # Start = 12
# # Stop = 0 (0 is not included)
# # Step = -1 (go backwards by 1)        

# list(range(12,0,-2))   

# # Output ::[12 , 10, 8, 6 , 4 , 2]



# # How Python  ::
# # Start = 12
# # Stop = 0 (0 is not included)
# # Step = -2 (go backwards by 2)


""""SEQUENCE IN PYTHON""" 


# A sequence is an ordered collection of items.
# Examples of sequences: String, List, Tuple

"""list""" 
# numbers = [10, 20, 30, 40]

#prices = [99.99, 149.50, 250.75]

#student = ["Vishal", 19, 85.5, True]

#status = [True, False, True]
 
# State =["uttarpradesh", "bihar", "assam", "gujarat"]


"""HOW TO CREATE A LIST """


""" List Created Using list()

letters = list("Python")

Output:

['P', 'y', 't', 'h', 'o', 'n'] """



# for x in "vishal":
#     print(x)
# OUTPUT:
# v
# i
# s
# h
# a
# l 
    
    
    
"""
List → [1, 2, 3]
String → "Python"
Tuple → (1, 2, 3)
Range → range(5)"""

for x in [2,3,4,5] :
    print(x)
    
# OUTPUT::: 
    
# 2
# 3
# 4
# 5        


""" STRING """

''' String (str)'''

#Text (Most Common)

name = "Vishal"

#Numbers as Text

number = "12345"

#Special Characters
symbols = "@#$%^&*"

#Mixed Characters
password = "Vishal@123"

#Empty String
empty = ""




""" Tuple """

''' Tuple (tuple)'''

#Tuple of Numbers
numbers = (10, 20, 30, 40)


#Tuple of Strings
states = ("Uttar Pradesh", "Bihar", "Assam", "Gujarat")


#Tuple of Floats
prices = (99.99, 149.50, 250.75)


#Tuple of Booleans
status = (True, False, True)


#Mixed Data Types
student = ("Vishal", 19, 85.5, True)

#Empty Tuple
empty = ()


#Nested Tuple
matrix = ((1, 2), (3, 4), (5, 6))


#Tuple with Duplicate Values
colors = ("Red", "Blue", "Red", "Green")





'''Difference Between List and Tuple'''
""" A list is mutable (changeable), whereas a tuple is immutable (unchangeable)."""



# | List              | Tuple                |
# | ----------------- | -------------------- |
# | **Mutable**       | **Immutable**        |
# | Can add items     | Cannot add items     |
# | Can remove items  | Cannot remove items  |
# | Can replace items | Cannot replace items |
# | Uses `[]`         | Uses `()`            |

'''
Quick Summary

Data Type	Can Store

String (str)	=> Text/characters (letters, digits, symbols)
Tuple (tuple)=>	Numbers, strings, floats, booleans, mixed data types, nested tuples


Easy Memory Trick 🧠


String → Stores text (characters).
List → Stores multiple items (can be changed).
Tuple → Stores multiple items (cannot be changed).'''

